name: binance-trading-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - requests
  - pip
  - python-binance
  - redis==5.2.1
  - pip:
      - ta
      - plotly